all:
  exclude:
    - 'spec/**/*'
    - 'app/assets/**/*'

github:
  slug: vinhnq-fooder-io/publify
  access_token: ENV["GITHUB_ACCESS_TOKEN"]
  api_endpoint: https://api.github.com/
  web_endpoint: https://github.com/
max_warnings: 150
warnings_per_review: 30
verbose: false
runners: [rubocop]
