exclude_paths:
  - 'db/migrate'
  - 'publify_amazon_sidebar/spec/dummy/db/migrate'
  - 'publify_textfilter_code/spec/dummy/db/migrate'
  - 'publify_core/db/migrate'
directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/models":
    IrresponsibleModule:
      enabled: false
