# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 189eafa373f70c3f770798b832dd5e48e3042c03639a6a1dc952c6b88eaed9b418d010874932a5f1b1d1d0453102160190729d1a04c453f9eb3639073c645311

test:
  secret_key_base: 81a64773cabdd99b20a666b0d1cbe69b27cd3eb6ea3213740016c8dff97f69d56ac092fb50c9a20b6c64e32b066d4970e4a1dc2d44c87b0dd86b5eea98a0a181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
